src/Entity/Cars.php
<?php

namespace App\Entity;

use App\Repository\CarsRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Uid\UuidV7 as Uuid;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: CarsRepository::class)]
#[ORM\Table(name: "cars")]
class Cars
{
    #[ORM\Id]
    #[ORM\Column(type: 'uuid', unique: true)]
    #[ORM\GeneratedValue(strategy: 'CUSTOM')]
    #[ORM\CustomIdGenerator(class: 'doctrine.uuid_generator')]
    private ?Uuid $id;

    #[Assert\NotBlank()]
    #[ORM\Column(length: 50)]
    private ?string $title;

    #[Assert\NotNull()]
    #[ORM\Column]
    private ?int $price;

    #[Assert\Type(type: 'digit', message: "L'année doit être un nombre.")]
    #[Assert\Length(min: 4, max: 4, exactMessage: "L'année doit être composée de 4 chiffres.")]
    #[Assert\Range(
        min: 1770,
        max: "this_year",
        notInRangeMessage: "L'année doit être comprise entre 1770 et l'année actuelle."
    )]
    #[ORM\Column(type: 'string', length: 4)]
    private ?string $year;

    #[Assert\NotNull()]
    #[ORM\Column]
    private ?int $mileage;

    #[Assert\NotNull()]
    #[ORM\Column]
    private ?int $puissance_din;

    #[Assert\NotNull()]
    #[ORM\Column]
    private ?int $puissance_fiscale;

    #[Assert\NotNull()]
    #[ORM\Column]
    private ?bool $isAutomatically;

    #[ORM\ManyToOne(targetEntity: MotorTechnologies::class)]
    #[ORM\JoinColumn(name: "motor_technologie", referencedColumnName: "id")]
    private ?MotorTechnologies $motorTechnologie = null;

    #[ORM\ManyToOne(targetEntity: Brands::class)]
    #[ORM\JoinColumn(name: "brand", referencedColumnName: "id")]
    private ?Brands $brand = null;

    #[ORM\OneToMany(targetEntity: Pictures::class, mappedBy: "car", cascade: ["remove"])]
    private Collection $pictures;

    #[ORM\OneToMany(targetEntity: Messages::class, mappedBy: "car", cascade: ["remove"])]
    private Collection $messages;

    public function __construct()
    {
        $this->pictures = new ArrayCollection();
        $this->messages = new ArrayCollection();
    }

    public function getId(): ?Uuid
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): static
    {
        $this->title = $title;

        return $this;
    }

    public function getPrice(): ?int
    {
        return $this->price;
    }

    public function setPrice(int $price): static
    {
        $this->price = $price;

        return $this;
    }

    public function getYear(): ?string
    {
        return $this->year;
    }

    public function setYear(string $year): static
    {
        $this->year = $year;

        return $this;
    }

    public function getMileage(): ?int
    {
        return $this->mileage;
    }

    public function setMileage(int $mileage): static
    {
        $this->mileage = $mileage;

        return $this;
    }

    public function getPuissanceDin(): ?int
    {
        return $this->puissance_din;
    }

    public function setPuissanceDin(int $puissance_din): static
    {
        $this->puissance_din = $puissance_din;

        return $this;
    }

    public function getPuissanceFiscale(): ?int
    {
        return $this->puissance_fiscale;
    }

    public function setPuissanceFiscale(int $puissance_fiscale): static
    {
        $this->puissance_fiscale = $puissance_fiscale;

        return $this;
    }

    public function isAutomatically(): ?bool
    {
        return $this->isAutomatically;
    }

    public function setAutomatically(bool $isAutomatically): static
    {
        $this->isAutomatically = $isAutomatically;

        return $this;
    }

    public function getMotorTechnologie(): ?MotorTechnologies
    {
        return $this->motorTechnologie;
    }

    public function setMotorTechnologie(?MotorTechnologies $motorTechnologie): static
    {
        $this->motorTechnologie = $motorTechnologie;

        return $this;
    }

    public function getBrand(): ?Brands
    {
        return $this->brand;
    }

    public function setBrand(?Brands $brand): static
    {
        $this->brand = $brand;

        return $this;
    }

    public function addPicture(Pictures $picture): self
    {
        if (!$this->pictures->contains($picture)) {
            $this->pictures[] = $picture;
            $picture->setCar($this);
        }

        return $this;
    }

    public function removePicture(Pictures $picture): self
    {
        if ($this->pictures->removeElement($picture)) {
            if ($picture->getCar() === $this) {
                $picture->setCar(null);
            }
        }

        return $this;
    }

    public function getPictures(): Collection
    {
        return $this->pictures;
    }

    public function addMessage(Messages $message): self
    {
        if (!$this->messages->contains($message)) {
            $this->messages[] = $message;
            $message->setCar($this);
        }

        return $this;
    }

    public function removeMessage(Messages $message): self
    {
        if ($this->messages->removeElement($message)) {
            if ($message->getCar() === $this) {
                $message->setCar(null);
            }
        }

        return $this;
    }

    public function getMessages(): Collection
    {
        return $this->messages;
    }
}

src/Entity/Pictures.php
<?php

namespace App\Entity;

use App\Repository\PicturesRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: PicturesRepository::class)]
#[ORM\Table(name: "pictures")]
class Pictures
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id;

    #[ORM\Column(length: 255)]
    private ?string $picture;

    #[ORM\Column]
    private ?bool $is_primary = false;

    #[ORM\ManyToOne(targetEntity: Cars::class, inversedBy: "pictures")]
    #[ORM\JoinColumn(name: "car", referencedColumnName: "id")]
    private ?Cars $car;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPicture(): ?string
    {
        return $this->picture;
    }

    public function setPicture(string $picture): static
    {
        $this->picture = $picture;

        return $this;
    }

    public function isIsPrimary(): ?bool
    {
        return $this->is_primary;
    }

    public function setIsPrimary(bool $is_primary): static
    {
        $this->is_primary = $is_primary;

        return $this;
    }

    public function getCar(): ?Cars
    {
        return $this->car;
    }

    public function setCar(?Cars $car): self
    {
        $this->car = $car;

        return $this;
    }
}

templates/pages/occasions/details.html.twig
{% extends 'base.html.twig' %}

{% block title %}Détails{% endblock %}

{% block body %}
<div class="container mt-5">
  <div id="carouselExampleControls" class="carousel slide" data-bs-ride="true">
    <div class="carousel-inner">
      {% set primaryPictureShown = false %}
      {% for picture in car.pictures %}
        {% if picture.isIsPrimary and not primaryPictureShown %}
          <div class="carousel-item active height-70">
            <div class="carousel-content custom-car-carousel">
              <img src="https://garage-v-parrot.s3.eu-west-3.amazonaws.com/img/uploads/{{ picture.picture }}" alt="Image principale de {{ car.title }}">
            </div>
          </div>
          {% set primaryPictureShown = true %}
        {% endif %}
      {% endfor %}
      {% for picture in car.pictures %}
        {% if not picture.isIsPrimary or (picture.isIsPrimary and not primaryPictureShown) %}
          <div class="carousel-item {% if loop.first and not primaryPictureShown %}active{% endif %} height-70">
            <div class="carousel-content custom-car-carousel">
              <img src="https://garage-v-parrot.s3.eu-west-3.amazonaws.com/img/uploads/{{ picture.picture }}" alt="Image de {{ car.title }}">
            </div>
          </div>
        {% endif %}
      {% endfor %}
      </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
      <span class="carousel-control-prev-icon button-c" aria-hidden="true"></span>
      <span class="visually-hidden">Précédent</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
      <span class="carousel-control-next-icon button-c" aria-hidden="true"></span>
      <span class="visually-hidden">Suivant</span>
    </button>
  </div>
</div>
<div class="container">
  <div class="row text-center my-2">
    <div class="col car-title">
      <h2>{{car.title}}</h2>
    </div>
  </div>
  <div class="row text-center">
    <div class="col">
      <p class="car-text">{{car.brand.property}} ● {{car.year}} ● {{car.mileage}}km ● {{car.motorTechnologie.property}} ● 
      {{car.puissanceDin}}ch ● {{car.puissanceFiscale}}CV ● {{ (car.isAutomatically == true) ? 'Automatique' : 'Manuelle' }}</p>
      <p class="car-price">Prix : {{car.price}}€</p>
    </div>
  </div>
</div>

<div class="container">
  <h1 class="text-center h1 h1-border pb-3">● Demandez-nous plus d'informations ●</h1>
    <form method="post" class="contact-details-form row g-3 fs-4 mt-4 form-p">
      <div class="col-md-6">
        <label for="lastname" class="form-label">Nom</label>
        <input type="text" name="lastname" class="form-control" maxlength="50" placeholder="Nom" required>
      </div>
      <div class="col-md-6">
        <label for="firstname" class="form-label">Prénom</label>
        <input type="text" name="firstname" class="form-control" maxlength="50" placeholder="Prénom" required>
      </div>
      <div class="col-md-6">
        <label for="email" class="form-label">Email</label>
        <input type="email" name="email" class="form-control" maxlength="255" placeholder="example@example.fr" required>
      </div>
      <div class="col-md-6">
        <label for="phone" class="form-label">Téléphone</label>
        <input type="text" name="phone" class="form-control" maxlength="20" placeholder="0600000000" required>
      </div>
      <div class="col-12">
        <label for="subject" class="form-label">Sujet</label>
        <input type="text" name="subject" class="form-control" maxlength="20" readonly value="{{ car.title }}">
      </div>
      <div class="col-12">
        <label for="comment" class="form-label">Commentaire</label>
        <textarea type="text" name="comment" class="form-control" id="area255" rows="5" placeholder="Max 255 caractères" maxlength="255" required></textarea>
        <p id="lengthValue255">0 / 255 caractères</p>
      </div>
      <div class="col-md-12 d-flex justify-content-center">
      <input type="hidden" name="_csrf_token" value="{{ csrf_token('contact-details-form') }}">
        <button type="submit" class="btn button-p fs-3 fw-medium">Envoyer un message</button>
      </div>
    </form>   
  </div>
</div>
<script src="{{ asset('assets/javascript/updateDivHeight.js') }}"></script>
<script src="{{ asset('assets/javascript/limitCharacters255.js') }}"></script>
{% endblock %}

templates/pages/occasions/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nos occasion{% endblock %}

{% block body %}
  <div class="container">
    {% for message in app.flashes('success') %}
      <div class="alert alert-success">{{ message }}</div>
    {% endfor %}

    {% for message in app.flashes('error') %}
      <div class="alert alert-danger">{{ message }}</div>
    {% endfor %}
  </div>

  <main>
    <div class="container mt-5">
      <h1 class="text-center mx-5 mb-5 h1">Nos voitures d'occasion</h1>
      <button id="toggleFiltersBtn" class="btn button-p">Ξ Filtres</button>
      <div id="filters" class="row my-3 justify-content-center">
        <div class="col-md-3 mt-3 mx-1">
          <label for="yearMin" class="form-label">Année min</label>
          <input type="number" class="form-control filter" id="yearMin">
        </div>
        <div class="col-md-3 mt-3 mx-1">
          <label for="yearMax" class="form-label">Année max</label>
          <input type="number" class="form-control filter" id="yearMax">
        </div>
        <div class="col-md-3 mt-3 mx-1">
          <label for="kmMin" class="form-label">Kilométrage min</label>
          <input type="number" class="form-control filter" id="kmMin">
        </div>
        <div class="col-md-3 mt-3 mx-1">
          <label for="kmMax" class="form-label">Kilométrage max</label>
          <input type="number" class="form-control filter" id="kmMax">
        </div>
        <div class="col-md-3 mt-3 mx-1">
          <label for="priceMin" class="form-label">Prix min</label>
          <input type="number" class="form-control filter" id="priceMin">
        </div>
        <div class="col-md-3 mt-3 mx-1">
          <label for="priceMax" class="form-label">Prix max</label>
          <input type="number" class="form-control filter" id="priceMax">
        </div>
      </div>
      <div id="carListContainer" class="row justify-content-around">
        {% for car in cars %}
        <div class="col-md-5 my-3 p-0 card">
          {% set primaryPicture = car.pictures|filter(picture => picture.isPrimary)|first %}
          {% if primaryPicture %}
            <img src="https://garage-v-parrot.s3.eu-west-3.amazonaws.com/img/uploads/{{ primaryPicture.picture }}" class="card-img-top w-100 img-fluid m-0 p-0 dynamic-height" alt="Car Image">
          {% endif %}
          <div class="card-body">
            <p class="card-title text-center fs-4">{{car.title}}</p>
            <p class="card-text text-center">Marque : {{car.brand.property}}</p>
            <p class="card-price text-center fs-4">{{car.price}}€</p>
            <p class="card-text text-center">Année: {{car.year}}</p>
            <p class="card-text text-center">{{car.mileage}}km</p>
            <a href="/occasions/{{car.id}}" class="btn button-p d-block">Plus de détails</a>
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
  </main>
  <script src="{{ asset('assets/javascript/filtersCars.js') }}"></script>
  <script src="{{ asset('assets/javascript/updateImageHeight.js') }}"></script>
  <script src="{{ asset('assets/javascript/toggleFiltersDisplay.js') }}"></script>
{% endblock %}